[theme]
primaryColor = "#00D4AA"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
port = 8501
address = "0.0.0.0"
enableCORS = true
enableXsrfProtection = false

[browser]
gatherUsageStats = false

