# Arquivo de configurações secretas para o Streamlit
# Salve este arquivo como: .streamlit/secrets.toml

[email]
username = "gabrielmattoscosta4@gmail.com"
password = "wayamxmlxjlawtjv" 
admin_email = "gabrielmattoscosta4@gmail.com"